ItemEvents.tooltip(event => {
    event.add([
        //基础武器
        'rogues:flint_dagger', 
        'rogues:iron_dagger', 
        'rogues:netherite_dagger',
        'rogues:diamond_dagger',
        'rogues:golden_dagger',
        //交易武器
        'magistuarmoryaddon:steel_rondel_dagger',
        'magistuarmoryaddon:steel_parrying_dagger',
        'magistuarmoryaddon:steel_bollock_dagger',
        //独特武器
        'fantasy_weapons:weapon_thief_dagger',
        'fantasy_weapons:weapon_savage_dagger',
        'fantasy_weapons:weapon_old_dagger',
    ],
        Text.yellow('武器类型:匕首')
    )
    event.add([
    ],
        Text.yellow('武器类型:拳套')
    )
    event.add([
        //基础武器
        'rogues:iron_sickle',
        'rogues:golden_sickle',
        'rogues:diamond_sickle',
        'rogues:netherite_sickle',
        //交易武器
        'magistuarmoryaddon:steel_sickle',
    ],
        Text.yellow('武器类型:单手镰')
    )
    event.add([
        //基础武器
        'magistuarmory:gold_shortsword',
        'magistuarmory:wood_shortsword',
        'magistuarmory:stone_shortsword',
        'magistuarmory:iron_shortsword',
        'magistuarmory:copper_shortsword',
        'magistuarmory:diamond_shortsword',
        'magistuarmory:netherite_shortsword',
        //交易武器
        'magistuarmory:steel_shortsword',
        //独特武器
        'magistuarmory:silver_shortsword',
    ],
        Text.yellow('武器类型:短剑')
    )
    event.add([
        //基础武器        
        'minecraft:wooden_sword',
        'minecraft:golden_sword',
        'minecraft:diamond_sword',
        'minecraft:stone_sword',
        'composite_material:flint_sword',
        'composite_material:copper_sword',
        'minecraft:iron_sword',
        'composite_material:obsidian_sword',
        'minecraft:netherite_sword',
        //交易武器
        'magistuarmoryaddon:steel_arming_sword_type_xiv',
        'magistuarmoryaddon:steel_arming_sword_type_xv',
        'magistuarmoryaddon:steel_arming_sword_type_xiii',
        //独特武器
        'miningmaster:power_pyrite_sword',
        'miningmaster:lucky_citrine_sword',
        'miningmaster:spirit_garnet_sword',
        'miningmaster:ice_sapphire_sword',
        'miningmaster:fire_ruby_sword',
        'fantasy_weapons:weapon_old_blade',
        'composite_material:rusted_copper_sword',
        'composite_material:amethyst_sword',
    ],
        Text.yellow('武器类型:直剑')
    )
    event.add([
        //基础武器
        'simplyswords:netherite_spear',
        'simplyswords:diamond_spear',
        'simplyswords:gold_spear',
        'simplyswords:iron_spear',
        //交易武器
        'magistuarmory:pitchfork',
        //独特武器
        'fantasy_weapons:weapon_savage_spear',
    ],
        Text.yellow('武器类型:单手矛')
    )
    event.add([
        //基础武器
        'simplyswords:netherite_rapier',
        'simplyswords:diamond_rapier',
        'simplyswords:gold_rapier',
        'simplyswords:iron_rapier',
        //交易武器
        'magistuarmoryaddon:steel_rapier',
    ],
        Text.yellow('武器类型:迅捷剑')
    )
    event.add([
        //基础武器
        'minecraft:wooden_axe',
        'composite_material:flint_axe',
        'minecraft:stone_axe',
        'composite_material:copper_axe',
        'minecraft:iron_axe',
        'composite_material:obsidian_axe',
        'minecraft:diamond_axe',
        'minecraft:netherite_axe',
        'minecraft:golden_axe',
        //独特武器
        'composite_material:amethyst_axe',
        'composite_material:rusted_copper_axe',        
        'miningmaster:haste_peridot_axe',
        'miningmaster:power_pyrite_axe',
        'miningmaster:kinetic_opal_axe',
        //交易武器        
        'magistuarmoryaddon:steel_battleaxe',
        'magistuarmoryaddon:steel_francisca_axe',
        'magistuarmoryaddon:steel_war_axe',
    ],
        Text.yellow('武器类型:单手斧')
    )
    event.add([
        //基础武器        
        'magistuarmory:gold_heavymace',
        'magistuarmory:wood_heavymace',
        'magistuarmory:stone_heavymace',
        'magistuarmory:iron_heavymace',
        'magistuarmory:copper_heavymace',
        'magistuarmory:netherite_heavymace',
        'magistuarmory:diamond_heavymace',
        //交易武器
        'magistuarmoryaddon:steel_round_mace',
        'magistuarmory:steel_heavymace',
        //独特武器
        'fantasy_weapons:weapon_savage_hammer',
        'magistuarmory:rusted_heavymace',
        'magistuarmory:club',       
        'magistuarmory:silver_heavymace',                 
    ],
        Text.yellow('武器类型:单手杖')
    )
    event.add([
        //基础武器        
        'paladins:netherite_holy_wand',
        'paladins:diamond_holy_wand',
        'paladins:holy_wand',
        'paladins:acolyte_wand',
        'wizards:wand_netherite_frost',
        'wizards:wand_netherite_fire',
        'wizards:wand_netherite_arcane',
        'wizards:wand_frost',
        'wizards:wand_fire',
        'wizards:wand_arcane',
        'wizards:wand_novice',
        //独特武器        
        'mine_and_staff:iolite_staff',
        'mine_and_staff:roots_staff',
    ],
        Text.yellow('武器类型:单手魔杖')
    )
    event.add([
    ],
        Text.yellow('武器类型:魔导法器')
    )
    event.add([
        //基础武器        
        'minecraft:lantern',
        'any_lanterns:copper_lantern',
    ],
        Text.yellow('可魔导化为魔导法器')
    )
    event.add([
    ],
        Text.yellow('武器类型:魔导书')
    )
    event.add([
        //基础武器     
        'grimoireofgaia:weapon_book',
        //独特武器                   
        'grimoireofgaia:weapon_book_nature',
        'grimoireofgaia:weapon_book_battle',
    ],
        Text.yellow('可魔导化为魔导书')
    )
    event.add([
        //基础武器
        'wizards:staff_wizard',
        'wizards:staff_arcane',
        'wizards:staff_fire',
        'wizards:staff_netherite_arcane',
        'wizards:staff_netherite_fire',
        'paladins:netherite_holy_staff',
        'paladins:diamond_holy_staff',
        'paladins:holy_staff',
        'wizards:staff_netherite_frost',
        'wizards:staff_frost',
        //交易武器
        //独特武器
    ],
        Text.yellow('武器类型:双手魔杖')
    )
    event.add([
        //基础武器
        'archers:netherite_shortbow',
        'archers:mechanic_shortbow',
        'minecraft:bow',        
        //独特武器
        'mcdw:bow_bonebow',
        //交易武器
        'mcdw:bow_shortbow',                
    ],
        Text.yellow('武器类型:短弓')
    )
    event.add([
        //基础武器        
        'archers:royal_longbow',
        'archers:composite_longbow',
        //独特武器
        'mcdw:bow_hunting_bow',
        //交易武器
        'magistuarmory:longbow',        
    ],
        Text.yellow('武器类型:长弓')
    )
    event.add([
        //基础武器
        'archers:netherite_rapid_crossbow',
        'archers:rapid_crossbow',
        'minecraft:crossbow',
        //独特武器
        'mcdw:crossbow_dual_crossbow',
        //交易武器
    ],
        Text.yellow('武器类型:轻弩')
    )
    event.add([
        //基础武器
        'archers:netherite_heavy_crossbow',
        'archers:heavy_crossbow',
        //独特武器
        'mcdw:crossbow_butterfly_crossbow',
        //交易武器
        'magistuarmory:heavy_crossbow',
    ],
        Text.yellow('武器类型:重弩')
    )
    event.add([
    ],
        Text.yellow('武器类型:武士刀')
    )
    event.add([
        //基础武器
        'magistuarmory:netherite_bastardsword',
        'magistuarmory:copper_bastardsword',
        'magistuarmory:diamond_bastardsword',
        'magistuarmory:gold_bastardsword',
        'magistuarmory:stone_bastardsword',
        'magistuarmory:wood_bastardsword',
        'magistuarmory:iron_bastardsword',
        //独特武器
        'magistuarmory:noble_sword',
        'magistuarmory:silver_bastardsword',
        //交易武器
        'magistuarmory:steel_bastardsword',
    ],
        Text.yellow('武器类型:手半剑')
    )
    event.add([
        //基础武器
        'magistuarmory:diamond_pike',
        'magistuarmory:iron_pike',
        'magistuarmory:wood_pike',
        'magistuarmory:stone_pike',
        'magistuarmory:gold_pike',
        'magistuarmory:copper_pike',
        'magistuarmory:netherite_pike',
        //独特武器
        'magistuarmory:silver_pike',
        //交易武器
        'magistuarmory:steel_pike',
    ],
        Text.yellow('武器类型:长矛')
    )
    event.add([
    ],
        Text.yellow('武器类型:长柄刀')
    )
    event.add([
    ],
        Text.yellow('武器类型:长刀')
    )
    event.add([
    ],
        Text.yellow('武器类型:双手镰')
    )
    event.add([
    ],
        Text.yellow('武器类型:长柄斧')
    )
    event.add([
        //基础武器
        'magistuarmory:iron_concavehalberd',
        'magistuarmory:wood_concavehalberd',
        'magistuarmory:stone_concavehalberd',
        'magistuarmory:gold_concavehalberd',
        'magistuarmory:diamond_concavehalberd',
        'magistuarmory:copper_concavehalberd',
        'magistuarmory:netherite_concavehalberd',
        //独特武器
        'magistuarmory:silver_concavehalberd',
        //交易武器
        'magistuarmory:steel_concavehalberd',
    ],
        Text.yellow('武器类型:长戟')
    )
    event.add([
        //基础武器
        'magistuarmory:netherite_zweihander',
        'magistuarmory:copper_zweihander',
        'magistuarmory:diamond_zweihander',
        'magistuarmory:gold_zweihander',
        'magistuarmory:stone_zweihander',
        'magistuarmory:wood_zweihander',
        'magistuarmory:iron_zweihander',
        //独特武器
        'magistuarmory:silver_zweihander',
        'fantasy_weapons:weapon_sharp_sword',
        'fantasy_weapons:weapon_cursed_blade',
        //交易武器
        'magistuarmory:steel_zweihander',
    ],
        Text.yellow('武器类型:双手巨剑')
    )
    event.add([
        'simplyswords:iron_greataxe',
        'simplyswords:gold_greataxe',
        'simplyswords:diamond_greataxe',
        'simplyswords:netherite_greataxe',
    ],
        Text.yellow('武器类型:巨斧')
    )
    event.add([
    ],
        Text.yellow('武器类型:重型战锤')
    )
    event.add([
    ],
        Text.yellow('武器类型:双头刀')
    )
    event.add([
    ],
        Text.yellow('武器类型:环刃')
    )
    event.add([
    ],
        Text.yellow('武器类型:战刃')
    )
    event.add([
    ],
        Text.yellow('武器类型:独特')
    )
})
